const googleAdsId = 'AW-18415875509';
const defaultLeadConversionLabel = 'rDHlCKvGk-ocELXrr81E';
const leadConversionLabel = import.meta.env.VITE_GOOGLE_ADS_LEAD_CONVERSION_LABEL?.trim()
  || defaultLeadConversionLabel;

type GoogleTag = (command: 'event', eventName: 'conversion', parameters: {
  send_to: string;
}) => void;

type GoogleAdsWindow = Window & {
  gtag?: GoogleTag;
};

/**
 * Records a lead only after its phone number has been saved successfully.
 * The conversion label is generated by Google Ads when the conversion action
 * is created and is supplied at build time through the Vite environment.
 */
export const trackGoogleAdsLead = () => {
  if (typeof window === 'undefined' || !leadConversionLabel) return;

  const gtag = (window as GoogleAdsWindow).gtag;
  if (typeof gtag !== 'function') return;

  gtag('event', 'conversion', {
    send_to: `${googleAdsId}/${leadConversionLabel}`,
  });
};
