export const site = {
  url: 'https://ridepogon.com',
  name: 'Pogon',
  legalName: 'Pogon Mobility d.o.o.',
  phoneDisplay: '+381 63 15 05 003',
  phone: '+381631505003',
  email: 'pogonmobility@gmail.com',
  instagram: 'https://www.instagram.com/pogon.rs/',
  registeredAddress: {
    street: 'Temišvarska 25B',
    city: 'Beograd',
    country: 'RS',
  },
  published: '2026-09-20',
};

export const models = [
  {
    slug: 'cargo',
    name: 'Pogon Cargo',
    type: 'Električni bicikl za dostavu i teret',
    title: 'Pogon Cargo | Električni bicikl za dostavu i teret',
    description: 'Pogon Cargo električni bicikl za dostavu i teret: dve baterije, 1512 Wh, domet do 140 km, motor 250 W, široke gume i cena 130.000 RSD.',
    intro: 'Pogon Cargo je radni električni bicikl za gradske dostave, svakodnevne obaveze i prevoz stvari, sa dve baterije i širokim gumama za stabilnu vožnju.',
    image: '/Core main.jpg',
    imageWidth: 1086,
    imageHeight: 1448,
    imageAlt: 'Pogon Cargo električni bicikl za gradske dostave',
    gallery: [
      ['/Core 1.jpg', 'Pogon Cargo električni bicikl bočni prikaz', 1122, 1402],
      ['/Core 2.jpg', 'Detalj zadnjeg dela modela Pogon Cargo', 1122, 1402],
      ['/Core 3.jpg', 'Detalj rama električnog bicikla Pogon Cargo', 1122, 1402],
    ],
    price: 130000,
    priceDisplay: '130.000 RSD',
    listPrice: null,
    range: 'Do 140 km',
    battery: 'Dve baterije, ukupno 1512 Wh',
    motor: '250 W, u zadnjem točku',
    frame: 'Čelični ram',
    brakes: 'Hidraulične kočnice',
    tyres: 'Široke fat tyre gume',
    security: 'GPS sigurnosne funkcije',
    extraLabel: 'Namena',
    extraValue: 'Dostava, posao i prevoz stvari',
    forWhom: 'dostavljačima, malim firmama i vozačima koji često nose opremu ili druge stvari kroz grad',
    summary: 'Dve baterije · rad i dostava · do 140 km',
    body: [
      ['Za koga je Pogon Cargo?', '<p>Pogon Cargo je namenjen vozačima kojima bicikl nije samo rekreacija. Čelični ram, široke fat tyre gume i zadnji motor čine ga praktičnim za dostavljače, male firme i svakodnevni prevoz stvari kroz grad. Električna asistencija olakšava pokretanje i duže rute, naročito kada se bicikl koristi tokom većeg dela dana.</p><p>Pre kupovine razmislite o stvarnoj masi koju redovno nosite, mestu na kome ostavljate bicikl i dužini tipične smene. Pogon Cargo je radni izbor u ponudi; ako vam teret nije prioritet, <a href="/elektricni-bicikli/glide/">Pogon Glide</a> je više usmeren na klasičnu gradsku vožnju.</p>'],
      ['Baterija i realan domet', '<p>Dve baterije imaju ukupni deklarisani kapacitet od 1512 Wh, uz deklarisani domet do 140 km. Dve baterije smanjuju potrebu da se radni dan planira oko jednog punjenja, ali domet nije garantovana kilometraža.</p><p>Masa vozača i tereta, usponi, temperatura, vetar, pritisak u gumama, česta zaustavljanja i nivo asistencije menjaju potrošnju. Za poslovnu upotrebu planirajte rezervu umesto da rutu zasnivate na maksimalnoj vrednosti. Više primera nalazi se u <a href="/vodici/domet-elektricnog-bicikla/">vodiču o realnom dometu</a>.</p>'],
      ['Kontrola, ram i gume', '<p>Pogon Cargo koristi hidraulične kočnice i široke fat tyre gume. Šire gume mogu doprineti mirnijem prelasku preko oštećenog asfalta, ali stvaraju veći otpor i traže redovnu kontrolu pritiska. Hidraulične kočnice treba proveravati u skladu sa intenzitetom upotrebe, posebno kada se bicikl vozi sa teretom.</p><p>Čelični ram je deo radne konstrukcije modela. Pre prve smene podesite položaj sedenja, proverite pričvršćenje tereta i testirajte kočenje bez tereta, pa tek onda sa uobičajenim opterećenjem.</p>'],
    ],
    faq: [
      ['Kome je namenjen Pogon Cargo?', 'Pogon Cargo je namenjen gradskim dostavama, poslovnoj upotrebi i vozačima koji redovno prevoze opremu ili stvari.'],
      ['Koliki je domet sa dve baterije?', 'Deklarisani domet je do 140 km. Stvarni rezultat zavisi od tereta, terena, temperature, pritiska u gumama i nivoa asistencije.'],
      ['Da li Cargo ima hidraulične kočnice?', 'Da. Objavljena specifikacija modela Pogon Cargo navodi hidraulične kočnice i široke fat tyre gume.'],
      ['Kako mogu da kupim ili probam Cargo?', 'Pogon Cargo možete naručiti onlajn ili prethodno zakazati besplatnu test vožnju u dogovoru sa Pogon timom.'],
    ],
    related: ['elektricni-bicikl-za-dostavu', 'domet-elektricnog-bicikla', 'fat-tyre-elektricni-bicikl', 'odrzavanje-elektricnog-bicikla'],
  },
  {
    slug: 'core',
    name: 'Pogon Core',
    type: 'Sklopivi fat tyre električni bicikl',
    title: 'Pogon Core | Sklopivi fat tyre električni bicikl',
    description: 'Pogon Core sklopivi električni bicikl: dve baterije, 1512 Wh, domet do 140 km, široke gume, motor 250 W i cena 130.000 RSD.',
    intro: 'Pogon Core je sklopivi električni bicikl za grad i duže rute, namenjen vozačima kojima su važni praktično odlaganje, stabilnost i dve baterije.',
    image: '/Cargo Main.jpg',
    imageWidth: 1122,
    imageHeight: 1402,
    imageAlt: 'Pogon Core sklopivi električni bicikl sa širokim gumama',
    gallery: [
      ['/Cargo fold.jpg', 'Sklopljen Pogon Core električni bicikl', 1122, 1402],
      ['/Cargo 1.jpg', 'Pogon Core fat tyre električni bicikl bočni prikaz', 1122, 1402],
      ['/Cargo 2.jpg', 'Detalj modela Pogon Core', 1122, 1402],
    ],
    price: 130000,
    priceDisplay: '130.000 RSD',
    listPrice: '135.000 RSD',
    range: 'Do 140 km',
    battery: 'Dve baterije, ukupno 1512 Wh',
    motor: '250 W, u zadnjem točku',
    frame: 'Sklopivi čelični ram',
    brakes: 'Hidraulične kočnice',
    tyres: 'Široke fat tyre gume',
    security: 'GPS sigurnosne funkcije',
    extraLabel: 'Sklapanje',
    extraValue: 'Sklopivi ram za lakše odlaganje',
    forWhom: 'vozačima kojima su važni sklapanje, široke gume, dve baterije i duže gradske rute',
    summary: 'Sklopivi ram · fat tyre · do 140 km',
    body: [
      ['Za koga je Pogon Core?', '<p>Pogon Core spaja sklopivi čelični ram, široke gume i dve baterije. Namenjen je vozačima koji nemaju mnogo prostora za odlaganje ili povremeno žele da bicikl smeste u veći prtljažnik, ali ne žele mali gradski model sa jednom baterijom.</p><p>Sklapanje olakšava odlaganje, ali ne znači da je bicikl lagan za nošenje uz više spratova. Pre odluke proverite gde ćete ga čuvati i koliko često ćete ga stvarno podizati. Ako je klasična gradska geometrija važnija od sklapanja, uporedite ga sa modelom <a href="/elektricni-bicikli/glide/">Pogon Glide</a>.</p>'],
      ['Dve baterije i realan domet', '<p>Ukupni deklarisani kapacitet dve baterije iznosi 1512 Wh, a deklarisani maksimum dometa je do 140 km. To može smanjiti učestalost punjenja na tipičnim gradskim rutama i dati više rezerve za neplanirane obaveze.</p><p>Maksimalni domet nije obećanje za svaku vožnju. Nivo asistencije, teren, temperatura, masa vozača, vetar i pritisak u gumama menjaju rezultat. Ako želite da razumete kako se kapacitet poredi, pročitajte <a href="/vodici/baterija-elektricnog-bicikla/">vodič o baterijama, voltima, amper-satima i vat-satima</a>.</p>'],
      ['Sklopivi ram, kočnice i široke gume', '<p>Sklopivi čelični ram olakšava čuvanje u garaži, poslovnom prostoru ili stanu kada je podna površina ograničena. Mehanizam sklapanja treba zatvoriti i proveriti prema uputstvu pre svake vožnje posle transporta.</p><p>Objavljena specifikacija navodi hidraulične kočnice i široke fat tyre gume. Šire gume mogu doneti stabilniji osećaj na lošijem asfaltu, ali mogu povećati otpor kotrljanja. Pogledajte uravnotežen pregled u <a href="/vodici/fat-tyre-elektricni-bicikl/">vodiču o prednostima i manama širokih guma</a>.</p>'],
    ],
    faq: [
      ['Da li Pogon Core može da se sklopi?', 'Da. Pogon Core ima sklopivi čelični ram namenjen lakšem odlaganju i transportu.'],
      ['Koliki je domet Pogon Core bicikla?', 'Deklarisani domet sa dve baterije je do 140 km. Realan rezultat zavisi od terena, temperature, težine vozača, pritiska u gumama i nivoa asistencije.'],
      ['Da li Core ima hidraulične kočnice?', 'Da. Objavljena specifikacija modela Pogon Core navodi hidraulične kočnice.'],
      ['Kako mogu da kupim ili probam Core?', 'Pogon Core možete naručiti onlajn ili prethodno zakazati besplatnu test vožnju u dogovoru sa Pogon timom.'],
    ],
    related: ['sklopivi-elektricni-bicikl', 'fat-tyre-elektricni-bicikl', 'baterija-elektricnog-bicikla', 'domet-elektricnog-bicikla'],
  },
  {
    slug: 'glide',
    name: 'Pogon Glide',
    type: 'Gradski električni bicikl',
    title: 'Pogon Glide | Gradski električni bicikl do 90 km',
    description: 'Pogon Glide gradski električni bicikl: domet do 90 km, baterija 1200 Wh, aluminijumski ram, motor 250 W, NFC kartice i cena 165.000 RSD.',
    intro: 'Pogon Glide je gradski električni bicikl za posao, obaveze i svakodnevnu vožnju, sa aluminijumskim ramom, baterijom od 1200 Wh i NFC karticama.',
    image: '/Glide main.jpg',
    imageWidth: 941,
    imageHeight: 1672,
    imageAlt: 'Pogon Glide gradski električni bicikl',
    gallery: [
      ['/Glide 1.jpg', 'Pogon Glide gradski električni bicikl bočni prikaz', 1254, 1254],
      ['/Glide 2.jpg', 'Detalj rama električnog bicikla Pogon Glide', 1254, 1254],
      ['/Glide 4.jpg', 'Detalj sedišta i zadnjeg dela modela Pogon Glide', 1254, 1254],
    ],
    price: 165000,
    priceDisplay: '165.000 RSD',
    listPrice: null,
    range: 'Do 90 km',
    battery: '1200 Wh',
    motor: '250 W, u zadnjem točku',
    frame: 'Aluminijumski ram',
    brakes: 'Tip nije naveden u objavljenoj specifikaciji',
    tyres: 'Gradske gume',
    security: 'GPS sigurnosne funkcije i NFC kartice za otključavanje',
    extraLabel: 'Nosivost',
    extraValue: 'Do 120 kg',
    forWhom: 'vozačima koji žele udoban električni bicikl za posao, kupovinu i svakodnevne gradske obaveze',
    summary: 'Aluminijumski ram · gradska vožnja · do 90 km',
    body: [
      ['Za koga je Pogon Glide?', '<p>Pogon Glide je namenjen vozačima koji žele prirodan položaj sedenja, mirnu vožnju i električnu asistenciju na svakodnevnim gradskim relacijama. Aluminijumski ram i gradska geometrija čine ga praktičnim za odlazak na posao, kupovinu i redovne obaveze.</p><p>Glide je najdirektniji gradski izbor u Pogon ponudi. Ako su vam važni sklapanje i široke gume, pogledajte <a href="/elektricni-bicikli/core/">Pogon Core</a>; ako redovno prevozite opremu ili radni teret, uporedite ga sa modelom <a href="/elektricni-bicikli/cargo/">Pogon Cargo</a>.</p>'],
      ['Baterija i realan domet', '<p>Baterija od 1200 Wh ima deklarisani domet do 90 km. Za mnoge gradske rute to znači više odlazaka između punjenja, ali stvarni rezultat zavisi od uslova vožnje.</p><p>Usponi, temperatura, masa vozača, vetar, pritisak u gumama i viši nivo asistencije mogu skratiti domet. Planirajte rezervu i posmatrajte potrošnju tokom prvih nekoliko tipičnih ruta. Detaljniji okvir pronaći ćete u <a href="/vodici/domet-elektricnog-bicikla/">vodiču o stvarnom dometu e-bicikla</a>.</p>'],
      ['Ram, otključavanje i provera kočnica', '<p>Aluminijumski ram i deklarisana nosivost do 120 kg predstavljaju ključne podatke za izbor. NFC kartice služe za praktično otključavanje, dok GPS sigurnosne funkcije dodaju sloj zaštite u svakodnevnoj upotrebi.</p><p>Tip kočnica nije naveden u trenutno objavljenoj specifikaciji modela Glide, pa ga ne pretpostavljamo. Kupac treba da ga potvrdi sa Pogon timom pre kupovine i da na test vožnji proveri osećaj na ručicama, modulaciju i zaustavljanje pri uobičajenoj brzini.</p>'],
    ],
    faq: [
      ['Koliki je domet Pogon Glide bicikla?', 'Deklarisani domet je do 90 km. Realan rezultat zavisi od terena, temperature, težine vozača, pritiska u gumama i nivoa asistencije.'],
      ['Kolika je nosivost modela Glide?', 'Deklarisana nosivost modela Pogon Glide je do 120 kg.'],
      ['Kako se otključava Pogon Glide?', 'Pogon Glide podržava NFC kartice za praktično otključavanje bicikla.'],
      ['Koji tip kočnica ima Glide?', 'Tip kočnica nije naveden u trenutno objavljenoj specifikaciji. Potvrdite taj podatak sa Pogon timom pre kupovine ili tokom test vožnje.'],
    ],
    related: ['elektricni-bicikl-za-grad', 'domet-elektricnog-bicikla', 'baterija-elektricnog-bicikla', 'odrzavanje-elektricnog-bicikla'],
  },
];

export const guides = [
  {
    slug: 'kako-izabrati-elektricni-bicikl',
    title: 'Kako izabrati električni bicikl: praktičan vodič',
    description: 'Praktičan vodič za izbor električnog bicikla prema ruti, dometu, bateriji, motoru, ramu, gumama, kočnicama, servisu i načinu odlaganja.',
    category: 'Izbor modela',
    direct: 'Pravi električni bicikl nije model sa najvećim brojem na papiru, već onaj koji odgovara vašoj tipičnoj ruti, prostoru za odlaganje i načinu korišćenja. Počnite od kilometraže i namene, zatim proverite bateriju, ram, gume, kočnice, težinu, servis i garanciju.',
    sections: [
      ['Krenite od namene, ne od specifikacije', '<p>Pre gledanja baterije i motora napišite kako će izgledati običan radni dan. Da li biciklom idete do posla, nosite dostavnu torbu, vozite se do stanice ili ga koristite za kupovinu? Model za ravnu rutu od pet kilometara ne mora biti isti kao model za višesatnu dostavu.</p><p>Razmislite i o učestalosti. Povremena vikend vožnja trpi više kompromisa nego svakodnevni odlazak na posao. Ako će bicikl zameniti automobil na većini gradskih ruta, udobnost, pouzdanost i mogućnost punjenja postaju važniji od izgleda.</p>'],
      ['Izmerite rutu i dodajte rezervu', '<p>Izmerite odlazak i povratak, pa dodajte neplanirane obaveze. Nemojte birati bateriju tako da deklarisani maksimum jedva pokriva dnevnu rutu. Domet zavisi od uspona, vetra, temperature, pritiska u gumama, tereta i nivoa asistencije.</p><p>Praktičniji pristup je da ostavite razumnu rezervu i da tokom prvih vožnji pratite koliko se baterija troši na vašoj ruti. Za detaljan okvir pogledajte <a href="/vodici/domet-elektricnog-bicikla/">kako se procenjuje stvarni domet električnog bicikla</a>.</p>'],
      ['Uporedite baterije preko Wh', '<p>Volti i amper-sati sami ne daju celu sliku. Množenjem napona i kapaciteta u amper-satima dobija se približan broj vat-sati, odnosno Wh. Taj broj je korisniji za osnovno poređenje energije koju baterija može da skladišti.</p><p>Veći kapacitet obično znači više energije, ali i veću masu, cenu i duže punjenje. Dve baterije mogu dati fleksibilnost na dugim danima, dok je jedna baterija često sasvim dovoljna za kraće gradske rute.</p>'],
      ['Motor i osećaj asistencije', '<p>Snaga u vatima nije jedina stvar koja određuje kako se bicikl ponaša. Važni su način isporuke snage, kontroler, senzori, prenos, ukupna masa i podešavanje nivoa asistencije. Motor od 250 W može biti dobro usklađen sa gradskom vožnjom, ali broj sam ne govori koliko će polazak biti prirodan ili kako će se bicikl ponašati na usponu.</p><p>Test vožnja je zato korisnija od poređenja samo jednog reda u tabeli. Probajte najniži i viši nivo asistencije, polazak iz mesta i kratko usporavanje.</p>'],
      ['Ram, položaj i skladištenje', '<p>Proverite visinu rama, položaj sedenja i koliko lako možete da siđete sa bicikla. Sklopivi ram štedi prostor, ali prvo proverite dimenzije sklopljenog bicikla i da li ćete ga često podizati. Materijal rama je samo deo priče; geometrija i podešavanje sedišta snažno utiču na udobnost.</p><p>Ako bicikl stoji u zajedničkoj garaži, planirajte kvalitetno zaključavanje. Ako ide u stan, izmerite vrata, lift i mesto na kome će se puniti.</p>'],
      ['Gume, kočnice i oprema', '<p>Široke gume mogu pružiti mirniji osećaj na lošijem asfaltu, ali stvaraju veći otpor, zauzimaju više prostora i traže pažnju pri izboru pritiska. Uže gradske gume su lakše i efikasnije na dobrom asfaltu. Ne postoji univerzalno bolji izbor.</p><p>Kočnice moraju odgovarati masi bicikla, terenu i teretu. Proverite tip, dostupnost potrošnih delova i osećaj na ručicama. Svetla, blatobrani, prtljažnik, retrovizor i držač telefona mogu biti važniji za svakodnevicu od retko korišćene dodatne funkcije.</p>'],
      ['Servis, garancija i ukupna vrednost', '<p>Pitajte šta garancija pokriva, kako se prijavljuje problem i gde se obavlja servis. Proverite dostupnost pločica, guma, punjača i drugih potrošnih delova. Najniža početna cena nije nužno najniži trošak tokom nekoliko godina.</p><p>Pogon navodi dve godine garancije i servisnu podršku u više gradova; tačnu lokaciju, uslove i radno vreme treba potvrditi direktno. Za opšti raspored kontrola pročitajte <a href="/vodici/odrzavanje-elektricnog-bicikla/">vodič za održavanje e-bicikla</a>.</p>'],
      ['Koji Pogon model odgovara kojoj nameni?', '<p><a href="/elektricni-bicikli/glide/">Pogon Glide</a> je usmeren na klasičnu gradsku vožnju, aluminijumski ram i svakodnevne obaveze. <a href="/elektricni-bicikli/core/">Pogon Core</a> kombinuje sklopivi ram, široke gume i dve baterije. <a href="/elektricni-bicikli/cargo/">Pogon Cargo</a> je radni model za dostavu i prevoz stvari.</p><p>Najbolji sledeći korak je da izdvojite dva modela koja odgovaraju vašoj nameni, pa ih uporedite prema ruti i prostoru. Ako je moguće, zakažite test vožnju sa istim rancem ili teretom koji obično nosite.</p>'],
    ],
    faq: [
      ['Koliki domet treba da izaberem?', 'Birajte kapacitet sa rezervom u odnosu na svakodnevnu povratnu rutu. Maksimalni deklarisani domet nemojte tretirati kao garantovanu kilometražu.'],
      ['Da li je sklopivi e-bicikl uvek lak za nošenje?', 'Ne. Sklapanje smanjuje prostor potreban za odlaganje, ali masa bicikla i dalje određuje koliko ga je lako nositi uz stepenice.'],
      ['Da li su fat tyre gume bolje za grad?', 'Zavisi od podloge i prioriteta. Mogu biti udobnije na neravninama, ali obično imaju veći otpor i masu od užih gradskih guma.'],
      ['Da li treba probati bicikl pre kupovine?', 'Da, kada je moguće. Test vožnja otkriva položaj sedenja, ponašanje asistencije, osećaj kočnica i praktičnost koje tabela ne može potpuno da pokaže.'],
    ],
    related: ['domet-elektricnog-bicikla', 'baterija-elektricnog-bicikla', 'elektricni-bicikl-za-grad'],
  },
  {
    slug: 'koliko-kosta-elektricni-bicikl-mesecno',
    title: 'Koliko košta vožnja električnog bicikla mesečno?',
    description: 'Kako izračunati mesečni trošak električnog bicikla bez izmišljanja cena: struja, održavanje, potrošni delovi i poređenje sa drugim prevozom.',
    category: 'Troškovi',
    direct: 'Mesečni trošak e-bicikla zavisi od pređene kilometraže, potrošnje energije, vaše tarife električne energije i održavanja. Najpošteniji obračun koristi vašu cenu po kWh i stvarnu potrošnju, a ne jednu univerzalnu cifru.',
    sections: [
      ['Zašto ne postoji jedna tačna mesečna cena', '<p>Dve osobe mogu imati isti bicikl, a potpuno različit trošak. Jedna prelazi 100 km mesečno po ravnom asfaltu, druga 1.000 km sa teretom i čestim kočenjem. Razlikuju se i tarifa električne energije, pritisak u gumama, navike punjenja i učestalost servisa.</p><p>Zato je korisnije napraviti lični model troška. U njega ulaze energija, planirano održavanje, potrošni delovi i povremene popravke. Cena kupovine može se posmatrati odvojeno ili rasporediti na očekivani period korišćenja.</p>'],
      ['Formula za trošak struje', '<p>Prvo pretvorite kapacitet baterije u kWh: 1.000 Wh je približno 1 kWh. Zatim procenite koliko punih ekvivalenata punjenja napravite mesečno. Mesečna energija je kapacitet u kWh pomnožen brojem punjenja. Dobijeni broj pomnožite cenom jednog kWh sa svog računa.</p><div class="callout"><strong>Primer formule, bez fiksne cene:</strong>kapacitet baterije u kWh × broj punih punjenja mesečno × vaša cena kWh = približan mesečni trošak energije.</div><p>Punjač ima gubitke, pa energija povučena iz mreže može biti nešto veća od nominalnog kapaciteta baterije. Za kućnu procenu možete dodati rezervu, a za precizniji račun koristiti merač potrošnje.</p>'],
      ['Održavanje koje treba planirati', '<p>Redovno proveravanje pritiska u gumama i lanca košta malo, ali zanemarivanje povećava habanje. U mesečni budžet ima smisla rasporediti godišnji ili periodični servis, čak i ako se ne plaća svakog meseca.</p><p>Najčešći potrošni delovi su kočione pločice, gume, unutrašnje gume ili zaptivni materijal, lanac i elementi prenosa. Njihov vek zavisi od kilometraže, vremena, tereta i stila vožnje. Dostava i vožnja po kiši obično traže češće kontrole.</p>'],
      ['Kako rasporediti povremene troškove', '<p>Ako godišnje planirate određeni iznos za servis i delove, podelite ga sa 12. Tako dobijate rezervu umesto iznenadnog velikog računa. Isto možete uraditi sa kacigom, lancem za zaključavanje i drugom opremom koja traje duže od jednog meseca.</p><p>Baterija je dugoročan deo budžeta, ali njen vek nije fiksan broj meseci. Zavisi od hemije, temperature, dubine pražnjenja, skladištenja i broja ciklusa. Ne treba je automatski tretirati kao mesečni trošak, ali ima smisla planirati rezervu na duži rok.</p>'],
      ['Poređenje sa automobilom ili javnim prevozom', '<p>Za automobil saberite gorivo, parking, redovno održavanje, registraciju, osiguranje i deo troška amortizacije. Zatim izdvojite samo gradske kilometre koje bi e-bicikl realno mogao da zameni. Nije pošteno pretpostaviti da će bicikl zameniti svako putovanje.</p><p>Za javni prevoz koristite cenu karte ili mesečne pretplate koju stvarno plaćate. U poređenje uključite vreme do stanice, presedanje i dane kada zbog vremena ili obaveza ipak koristite drugi prevoz. Cilj nije marketinška cifra, već odluka koja odgovara vašoj rutini.</p>'],
      ['Jednostavna tabela za lični obračun', '<table class="data-table"><thead><tr><th>Stavka</th><th>Kako se računa</th><th>Vaš podatak</th></tr></thead><tbody><tr><td>Struja</td><td>kWh mesečno × cena kWh</td><td>Sa računa za struju</td></tr><tr><td>Redovan servis</td><td>Godišnji plan ÷ 12</td><td>Procena servisa</td></tr><tr><td>Potrošni delovi</td><td>Godišnji plan ÷ 12</td><td>Prema kilometraži</td></tr><tr><td>Oprema</td><td>Cena ÷ očekivani broj meseci</td><td>Kaciga, lanac, svetla</td></tr><tr><td>Alternativni prevoz</td><td>Dani korišćenja × stvarna cena</td><td>Javni prevoz ili automobil</td></tr></tbody></table><p>Ažurirajte tabelu posle dva ili tri meseca stvarne vožnje. Tada ćete imati podatke koji vrede više od opšte internet procene.</p>'],
      ['Kako modeli utiču na račun', '<p>Veća baterija skladišti više energije, ali trošak jednog punjenja i dalje zavisi od vaše tarife. <a href="/elektricni-bicikli/core/">Pogon Core</a> i <a href="/elektricni-bicikli/cargo/">Pogon Cargo</a> imaju dve baterije ukupnog kapaciteta 1512 Wh, dok <a href="/elektricni-bicikli/glide/">Pogon Glide</a> ima bateriju od 1200 Wh. To ne znači da svako punjenje kreće od nule niti da se puna energija troši svakog dana.</p><p>Za poslovnu upotrebu važni su i vreme bez vožnje, dostupnost punjenja i habanje pri teretu. U tom slučaju računajte trošak po radnom kilometru, a ne samo mesečni račun za struju.</p>'],
    ],
    faq: [
      ['Da li je punjenje e-bicikla skupo?', 'Trošak se računa iz kapaciteta baterije, broja punjenja i vaše cene električne energije. Bez tačne tarife nije odgovorno navesti jednu univerzalnu cifru.'],
      ['Koji trošak ljudi najčešće zaborave?', 'Često se zaboravljaju potrošni delovi, periodični servis i oprema za sigurnost i zaključavanje.'],
      ['Kako da uporedim e-bicikl sa automobilom?', 'Pored goriva uključite parking, održavanje, registraciju, osiguranje i samo one kilometre koje bicikl zaista može da zameni.'],
    ],
    related: ['baterija-elektricnog-bicikla', 'odrzavanje-elektricnog-bicikla', 'kako-izabrati-elektricni-bicikl'],
  },
  {
    slug: 'domet-elektricnog-bicikla',
    title: 'Koliki je stvarni domet električnog bicikla?',
    description: 'Šta utiče na stvarni domet električnog bicikla: kapacitet baterije u Wh, masa, usponi, temperatura, vetar, gume, asistencija i teret.',
    category: 'Baterija i domet',
    direct: 'Stvarni domet nije jedna fiksna kilometraža. Počinje od energije u bateriji, izražene u Wh, a zatim ga menjaju nivo asistencije, masa, usponi, temperatura, vetar, gume, zaustavljanja i teret.',
    sections: [
      ['Zašto „do” nije obećanje', '<p>Deklarisani domet obično opisuje najbolji ili standardizovani scenario. Vaša ruta se razlikuje po temperaturi, visinskoj razlici, brzini i teretu, pa rezultat može biti manji. To ne znači automatski da je baterija neispravna.</p><p>Korisnije je posmatrati raspon i rezervu. Ako dnevno prelazite 30 km, model čiji je maksimum tačno 30 km nije dobar plan. Ostavite prostor za vetar, hladnoću, obilazak i starenje baterije.</p>'],
      ['Wh je polazna tačka', '<p>Vat-sat, odnosno Wh, opisuje približnu količinu energije u bateriji. Dobija se množenjem napona u voltima sa kapacitetom u amper-satima. Baterija od 48 V i 25 Ah ima nominalno oko 1.200 Wh.</p><p>Wh omogućava osnovno poređenje, ali dva bicikla sa istim kapacitetom ne moraju preći istu udaljenost. Efikasnost motora, kontroler, gume, masa i način vožnje ostaju važni.</p>'],
      ['Masa vozača i tereta', '<p>Veća ukupna masa traži više energije pri ubrzanju i na usponima. Kod dostave treba računati i torbu, robu, korpu ili drugu opremu. Česta zaustavljanja dodatno povećavaju potrošnju jer se masa ponovo ubrzava.</p><p>Ako birate radni model, procenjujte domet sa stvarnim teretom. <a href="/elektricni-bicikli/cargo/">Pogon Cargo</a> ima dve baterije i deklarisani domet do 140 km, ali teret ostaje jedan od ključnih faktora stvarnog rezultata.</p>'],
      ['Usponi, brzina i nivo asistencije', '<p>Uspon je energetski zahtevniji od ravne rute. Viši nivo asistencije olakšava pedalanje, ali brže troši bateriju. Velika brzina povećava otpor vazduha, naročito kada je položaj vozača uspravan.</p><p>Za veći domet koristite niži nivo asistencije kada je teren lak, menjajte brzine pre uspona i održavajte ravnomeran ritam. Motor ne treba da nadoknađuje pogrešan prenos pri svakom polasku.</p>'],
      ['Temperatura, vetar i pritisak u gumama', '<p>Hladno vreme može privremeno smanjiti raspoloživu energiju i povećati unutrašnji otpor baterije. Čeoni vetar povećava potrošnju i kada je ruta ravna. Prenizak pritisak u gumama povećava otpor kotrljanja, dok previsok može smanjiti udobnost i kontakt na lošoj podlozi.</p><p>Koristite pritisak u okviru oznake proizvođača gume i prilagodite ga opterećenju. Proveravajte ga redovno, ne tek kada guma izgleda prazno.</p>'],
      ['Kako da izmerite svoj realan domet', '<ol><li>Napunite bateriju prema uputstvu i zabeležite početni nivo.</li><li>Vozite tipičnu rutu u uobičajenom nivou asistencije.</li><li>Zabeležite kilometre, temperaturu, teret i procenat potrošnje.</li><li>Ponovite merenje nekoliko puta.</li><li>Planirajte rezervu umesto korišćenja procenjenog maksimuma.</li></ol><p>Jedna vožnja nije dovoljna. Posle nekoliko ponavljanja dobićete lični raspon za leto, hladnije vreme i različita opterećenja.</p>'],
      ['Kako se razlikuju Pogon modeli', '<table class="data-table"><thead><tr><th>Model</th><th>Baterija</th><th>Deklarisani domet</th><th>Glavna namena</th></tr></thead><tbody><tr><td><a href="/elektricni-bicikli/core/">Pogon Core</a></td><td>Dve, ukupno 1512 Wh</td><td>Do 140 km</td><td>Sklopivi fat tyre model</td></tr><tr><td><a href="/elektricni-bicikli/cargo/">Pogon Cargo</a></td><td>Dve, ukupno 1512 Wh</td><td>Do 140 km</td><td>Dostava i prevoz stvari</td></tr><tr><td><a href="/elektricni-bicikli/glide/">Pogon Glide</a></td><td>1200 Wh</td><td>Do 90 km</td><td>Svakodnevna gradska vožnja</td></tr></tbody></table><p>Brojevi su deklarisani maksimumi iz objavljenih specifikacija. Za odluku ih uvek povežite sa svojom rutom.</p>'],
    ],
    faq: [
      ['Da li veća baterija uvek znači veći domet?', 'Obično daje više raspoložive energije, ali domet i dalje zavisi od mase, motora, guma, terena, temperature i načina vožnje.'],
      ['Zašto je domet manji zimi?', 'Niska temperatura može privremeno smanjiti raspoloživu energiju baterije, a gušći vazduh, odeća i uslovi na putu mogu povećati potrošnju.'],
      ['Kako da povećam domet?', 'Održavajte pritisak u gumama, koristite odgovarajući prenos, smanjite nivo asistencije kada nije potreban i izbegavajte nepotreban teret.'],
      ['Da li treba prazniti bateriju do kraja?', 'Za litijumske baterije potpuno pražnjenje obično nije potrebno za svakodnevnu upotrebu. Pratite uputstvo konkretnog proizvođača.'],
    ],
    related: ['baterija-elektricnog-bicikla', '250w-elektricni-bicikl', 'kako-izabrati-elektricni-bicikl'],
  },
  {
    slug: 'baterija-elektricnog-bicikla',
    title: 'Baterija električnog bicikla: kapacitet, punjenje i vek trajanja',
    description: 'Razumljivo objašnjenje V, Ah i Wh, punjenja, skladištenja, temperature i navika koje pomažu da baterija električnog bicikla traje.',
    category: 'Baterija i domet',
    direct: 'Za poređenje baterija najkorisniji je broj vat-sati (Wh). Dobija se približno množenjem napona (V) i kapaciteta (Ah), a pokazuje koliko energije baterija može da uskladišti.',
    sections: [
      ['Šta znače V, Ah i Wh?', '<p>Volti opisuju napon sistema. Amper-sati opisuju električni kapacitet, ali bez napona ne daju potpunu sliku energije. Vat-sati kombinuju oba podatka: V × Ah = Wh.</p><p>Na primer, 48 V × 25 Ah daje približno 1.200 Wh. To je nominalna vrednost; raspoloživa energija i ponašanje pod opterećenjem zavise od ćelija, elektronike, temperature i stanja baterije.</p>'],
      ['Zašto je Wh koristan za poređenje', '<p>Ako gledate samo Ah, baterija sa većim brojem može delovati snažnije iako radi na nižem naponu. Wh omogućava poštenije osnovno poređenje energije. Ipak, ne govori sve o kvalitetu ćelija, maksimalnoj struji, kućištu, masi ili kompatibilnosti.</p><p>Kapacitet nije isto što i domet. Za domet morate znati koliko Wh bicikl prosečno troši po kilometru u vašim uslovima.</p>'],
      ['Kako pravilno puniti bateriju', '<p>Koristite punjač namenjen konkretnoj bateriji i punite na suvom, stabilnom mestu, dalje od zapaljivih materijala i ekstremne toplote. Proverite kabl, konektor i kućište pre punjenja. Oštećenu ili neuobičajeno zagrejanu bateriju ne treba nastaviti koristiti bez stručne provere.</p><p>Pratite uputstvo proizvođača za redosled povezivanja i signalne lampice. Nemojte prekrivati punjač. Kada je punjenje završeno, isključite ga prema uputstvu umesto da baterija danima ostane bez potrebe priključena.</p>'],
      ['Skladištenje i temperatura', '<p>Bateriju čuvajte na suvom mestu bez velikih temperaturnih oscilacija. Duga izloženost velikoj toploti ubrzava starenje, dok veoma niska temperatura privremeno smanjuje performanse. Ako je baterija bila na hladnom, pustite je da postepeno dođe na sobnu temperaturu pre punjenja.</p><p>Za duže nekorišćenje pratite preporučen nivo napunjenosti iz uputstva. Nemojte je ostaviti potpuno praznu mesecima. Povremeno proverite stanje i dopunite prema preporuci proizvođača.</p>'],
      ['Šta utiče na vek trajanja', '<p>Vek zavisi od hemije ćelija, temperature, broja ciklusa, dubine pražnjenja, kvaliteta punjača i načina korišćenja. Jedan ciklus nije nužno jedno priključivanje na punjač; parcijalna pražnjenja zajedno čine puni ekvivalent ciklusa.</p><p>Ne postoji odgovorna univerzalna tvrdnja da će svaka baterija trajati tačno određen broj godina. Korisnije je pratiti pad dometa, ponašanje pod opterećenjem, vreme punjenja i eventualne fizičke promene.</p>'],
      ['Jedna ili dve baterije?', '<p>Jedna baterija je jednostavnija i lakša za tipičnu gradsku rutu. Dve baterije daju više ukupne energije i mogu smanjiti prekide tokom dugog dana, ali dodaju masu, cenu i više elemenata koje treba puniti i održavati.</p><p><a href="/elektricni-bicikli/core/">Pogon Core</a> i <a href="/elektricni-bicikli/cargo/">Pogon Cargo</a> navode dve baterije ukupnog kapaciteta 1512 Wh. <a href="/elektricni-bicikli/glide/">Pogon Glide</a> navodi jednu bateriju od 1200 Wh. Izbor treba vezati za rutu, a ne samo za najveći broj.</p>'],
      ['Znaci da je potrebna provera', '<ul><li>vidljivo oštećenje, deformacija ili curenje;</li><li>neuobičajeno zagrevanje tokom punjenja ili vožnje;</li><li>nagao pad prikazanog nivoa;</li><li>prekidi napajanja pod opterećenjem;</li><li>miris, zvuk ili ponašanje koje ranije nije postojalo.</li></ul><p>U tim situacijama prekinite korišćenje i obratite se kvalifikovanom servisu. Ne otvarajte kućište baterije bez odgovarajućeg znanja i opreme.</p>'],
    ],
    faq: [
      ['Kako se računa Wh baterije?', 'Približno pomnožite napon u voltima sa kapacitetom u amper-satima: V × Ah = Wh.'],
      ['Da li bateriju treba isprazniti pre svakog punjenja?', 'Ne nužno. Litijumske baterije se u praksi često dopunjavaju delimično. Uvek pratite uputstvo za konkretan model.'],
      ['Može li baterija da se puni odmah posle vožnje?', 'Ako je veoma topla ili hladna, sačekajte da postepeno dođe u umeren temperaturni opseg koji preporučuje proizvođač.'],
      ['Da li dve baterije traju dvostruko duže?', 'Daju više ukupne energije, ali stvarni domet nije nužno tačno dvostruk jer zavisi od mnogih uslova vožnje.'],
    ],
    related: ['domet-elektricnog-bicikla', 'odrzavanje-elektricnog-bicikla', 'koliko-kosta-elektricni-bicikl-mesecno'],
  },
  {
    slug: '250w-elektricni-bicikl',
    title: 'Šta znači 250 W kod električnog bicikla?',
    description: 'Tehničko objašnjenje oznake 250 W kod električnog bicikla: nominalna snaga, vršna snaga, obrtni moment, kontroler i odnos prema vožnji.',
    category: 'Tehnologija',
    direct: 'Oznaka 250 W najčešće opisuje trajnu nominalnu snagu motora, odnosno nivo na kome je projektovan da radi kontinuirano u propisanim uslovima. Sama oznaka ne opisuje ubrzanje, obrtni moment, domet niti pravnu kategoriju konkretnog vozila.',
    sections: [
      ['Snaga nije isto što i brzina', '<p>Vat je jedinica snage: pokazuje brzinu kojom se energija pretvara u rad. Veća snaga može pomoći pod opterećenjem, ali brzina zavisi i od prenosa, veličine točka, kontrolera, ograničenja sistema, mase i otpora.</p><p>Dva motora sa istom nominalnom oznakom mogu davati drugačiji osećaj. Jedan može imati mirniji polazak, drugi snažniji odziv, u zavisnosti od senzora i podešavanja.</p>'],
      ['Nominalna i vršna snaga', '<p>Nominalna snaga se odnosi na kontinuirani rad prema definiciji proizvođača ili relevantnog standarda. Vršna snaga je kratkotrajna vrednost koju sistem može dostići u određenim uslovima. Marketing ponekad ističe vršni broj bez jasnog konteksta.</p><p>Pri poređenju tražite istu vrstu podatka. Oznaku 250 W nemojte direktno porediti sa tuđom „peak” vrednošću bez tehničke dokumentacije.</p>'],
      ['Obrtni moment i polazak', '<p>Obrtni moment opisuje rotacionu silu. Važan je pri polasku, na usponu i sa teretom, ali ni on sam ne govori celu priču. Položaj motora, prenos, kontroler i prečnik točka menjaju kako se sila oseća na putu.</p><p>Ako često krećete uzbrdo ili nosite teret, test vožnja pod sličnim uslovima daje korisniji odgovor od jednog broja.</p>'],
      ['Senzor i kontroler', '<p>Senzor kadence prepoznaje okretanje pedala, dok senzor obrtnog momenta meri koliko snažno pritiskate. Različita podešavanja mogu učiniti asistenciju naglom ili prirodnom. Kontroler određuje koliko struje motor dobija i kako reaguje na komande.</p><p>Zbog toga „250 W” nije opis kompletnog pogonskog sistema. Udobnost zavisi i od softverskog podešavanja.</p>'],
      ['Uticaj na bateriju i domet', '<p>Motor ne troši stalno nominalnu snagu. Na ravnom putu uz lagano pedalanje potrošnja može biti manja; na usponu i visokom nivou asistencije veća. Ukupna potrošnja tokom rute izražava se energijom, odnosno Wh.</p><p>Za razumevanje odnosa pogledajte <a href="/vodici/baterija-elektricnog-bicikla/">vodič o kapacitetu baterije</a> i <a href="/vodici/domet-elektricnog-bicikla/">vodič o stvarnom dometu</a>.</p>'],
      ['Kako Pogon koristi oznaku 250 W', '<p>Objavljene specifikacije za <a href="/elektricni-bicikli/core/">Pogon Core</a>, <a href="/elektricni-bicikli/cargo/">Pogon Cargo</a> i <a href="/elektricni-bicikli/glide/">Pogon Glide</a> navode zadnji motor od 250 W. Razlike među modelima zato više treba tražiti u nameni, bateriji, ramu, gumama, nosivosti i praktičnim funkcijama.</p><p>Core je sklopivi fat tyre model, Cargo je namenjen radu i teretu, a Glide klasičnoj gradskoj vožnji.</p>'],
      ['Važna napomena o propisima', '<p>Snaga motora sama nije dovoljna da se utvrdi pravna kategorija, potrebna dokumentacija ili način korišćenja konkretnog vozila. Propisi i postupci mogu da se menjaju. Pre vožnje na javnom putu proverite važeće informacije i dokumentaciju konkretnog vozila.</p><p>Agencija za bezbednost saobraćaja u svojoj studiji o mikromobilnosti navodi 250 W u kontekstu pedelec standarda SRPS EN 15194, a u aktuelnim obaveštenjima naglašava da se klasifikacija oslanja na skup tehničkih karakteristika. Ovaj vodič nije pravni savet.</p>'],
    ],
    faq: [
      ['Da li 250 W znači maksimalnu snagu?', 'Ne nužno. Oznaka se često odnosi na trajnu nominalnu snagu; kratkotrajna vršna vrednost može biti drugačija.'],
      ['Da li 250 W određuje maksimalnu brzinu?', 'Ne samo po sebi. Brzina zavisi od prenosa, kontrolera, ograničenja sistema, točka, mase i drugih faktora.'],
      ['Da li su svi motori od 250 W isti?', 'Ne. Razlikuju se po obrtnom momentu, efikasnosti, senzorima, kontroleru, položaju i podešavanju asistencije.'],
      ['Da li 250 W automatski određuje pravni status?', 'Ne treba zaključivati samo iz snage. Proverite kompletnu tehničku dokumentaciju i aktuelne zvanične informacije.'],
    ],
    sources: [
      ['Studija o mikromobilnosti — Agencija za bezbednost saobraćaja', 'https://www.abs.gov.rs/static/uploads/13419_20220815092536-mikromobilnost_preporuke_za_implementaciju_final---1.pdf'],
      ['Aktuelno uputstvo za vozila sa dva točka sa elektromotorom — ABS', 'https://www.abs.gov.rs/rsl/uputstvo-za-vozila-sa-dva-tocka-sa-elektromotorom'],
    ],
    related: ['baterija-elektricnog-bicikla', 'domet-elektricnog-bicikla', 'kako-izabrati-elektricni-bicikl'],
  },
  {
    slug: 'sklopivi-elektricni-bicikl',
    title: 'Sklopivi električni bicikl: kome se isplati?',
    description: 'Prednosti i ograničenja sklopivog električnog bicikla: odlaganje, transport, masa, mehanizam sklapanja, udobnost i izbor modela.',
    category: 'Tipovi e-bicikala',
    direct: 'Sklopivi e-bicikl ima najviše smisla kada vam nedostaje prostor ili bicikl kombinujete sa automobilom, kancelarijom ili manjom ostavom. Sklapanje štedi prostor, ali ne znači automatski malu masu niti jednostavno nošenje uz stepenice.',
    sections: [
      ['Kada sklapanje rešava stvarni problem', '<p>Najbolji razlog za sklopivi model je konkretno ograničenje prostora. To može biti uzak hodnik, zajednička ostava, radni prostor ili potreba da se bicikl povremeno preveze automobilom. Ako imate veliku garažu i nikada ga ne transportujete, mehanizam možda nije presudna prednost.</p><p>Izmerite vrata, lift i planirano mesto. Proverite dimenzije kada je bicikl sklopljen i gde ostaju pedale, upravljač i točkovi.</p>'],
      ['Sklopiv ne znači nužno lagan', '<p>Električni motor, baterija, široke gume i čvrst ram dodaju masu. Bicikl može zauzimati manje prostora, a i dalje biti težak za nošenje. Ako živite bez lifta, tražite tačnu masu i probajte da ga podignete pre kupovine.</p><p>Razmislite i o hvatištu. Neki sklopivi bicikli se lako kotrljaju kada su delimično sklopljeni, dok druge morate nositi.</p>'],
      ['Mehanizam sklapanja i svakodnevna kontrola', '<p>Šarka i sigurnosni zatvarač su konstrukcijski važni. Posle sklapanja proverite da je mehanizam potpuno zatvoren i zaključan prema uputstvu. Obratite pažnju na zazor, neobične zvuke ili promenu položaja.</p><p>Ne podmazujte ili podešavajte sigurnosni mehanizam nasumično. Ako primetite promenu, zatražite stručnu proveru.</p>'],
      ['Veličina točkova, gume i udobnost', '<p>Sklopivi modeli nisu svi isti. Manji točkovi čine paket kompaktnijim, ali mogu drugačije reagovati na rupe i ivičnjake. Šire gume mogu ublažiti deo neravnina, uz cenu većeg otpora i mase.</p><p>Probajte poznatu neravninu na maloj brzini, proverite položaj upravljača i da li se sedište podešava za vašu visinu.</p>'],
      ['Baterija i kablovi pri sklapanju', '<p>Proverite da li se baterija vadi i da li sklapanje zateže kablove. Konektori ne treba da nose težinu ili da se savijaju pod oštrim uglom. Ako se bicikl prevozi u automobilu, zaštitite kontakte od prljavštine i vlage.</p><p>Vađenje baterije može smanjiti masu pri unošenju, ali samo ako proizvođač predviđa takvu upotrebu.</p>'],
      ['Pogon Core kao primer', '<p><a href="/elektricni-bicikli/core/">Pogon Core</a> ima sklopivi čelični ram, široke fat tyre gume, hidraulične kočnice i dve baterije ukupnog kapaciteta 1512 Wh. Deklarisani domet je do 140 km.</p><p>To ga pozicionira kao sklopivi model za vozače kojima su domet i stabilnost važni, a ne kao ultra-laki bicikl za svakodnevno nošenje. Zato na test vožnji proverite i sklapanje i podizanje, ne samo vožnju.</p>'],
      ['Kontrolna lista pre kupovine', '<ul><li>Izmerite prostor u kome će bicikl stajati.</li><li>Proverite masu sa i bez baterije.</li><li>Probajte mehanizam sklapanja više puta.</li><li>Proverite da kablovi nisu zategnuti.</li><li>Testirajte položaj sedenja i kočenje.</li><li>Proverite garanciju i servis mehanizma.</li></ul><p>Ako nijedna svakodnevna situacija ne zahteva sklapanje, uporedite i klasičan gradski model.</p>'],
    ],
    faq: [
      ['Da li sklopivi e-bicikl staje u svaki automobil?', 'Ne. Dimenzije se razlikuju, pa pre kupovine uporedite sklopljene mere sa otvorom i prostorom vašeg prtljažnika.'],
      ['Da li sklopivi model može na duge rute?', 'Može ako su baterija, geometrija i udobnost odgovarajući, ali to treba proveriti na konkretnom modelu.'],
      ['Koliko često treba proveravati šarku?', 'Vizuelno je proverite posle svakog sklapanja i pre vožnje. Za podešavanje i servis pratite uputstvo proizvođača.'],
    ],
    related: ['fat-tyre-elektricni-bicikl', 'kako-izabrati-elektricni-bicikl', 'odrzavanje-elektricnog-bicikla'],
  },
  {
    slug: 'fat-tyre-elektricni-bicikl',
    title: 'Fat tyre električni bicikl: prednosti i mane širokih guma',
    description: 'Uravnotežen vodič kroz fat tyre električne bicikle: stabilnost i udobnost, ali i veća masa, otpor, održavanje i prostor za odlaganje.',
    category: 'Tipovi e-bicikala',
    direct: 'Široke fat tyre gume mogu dati stabilniji i udobniji osećaj na lošem asfaltu, ali nisu besplatna prednost: povećavaju masu, otpor kotrljanja, cenu zamene i prostor potreban za odlaganje.',
    sections: [
      ['Šta se smatra fat tyre gumom', '<p>Fat tyre je opis vrlo široke gume u odnosu na klasičnu gradsku ili trekking gumu. Tačna širina zavisi od proizvođača i točka, pa naziv sam nije tehnička specifikacija.</p><p>Šira kontaktna površina i veća zapremina vazduha menjaju osećaj vožnje. Pritisak ima veliki uticaj: prenizak povećava otpor i rizik oštećenja, previsok umanjuje deo udobnosti.</p>'],
      ['Prednost: mirniji osećaj na neravninama', '<p>Veća zapremina gume može ublažiti sitne neravnine, šahtove i oštećen asfalt. Šira guma može ulivati sigurnost vozaču koji prelazi između različitih gradskih površina.</p><p>To nije zamena za pažljivu vožnju. Ivičnjaci, rupe i šljunak i dalje zahtevaju smanjenje brzine, pravilan položaj tela i ispravne kočnice.</p>'],
      ['Prednost: stabilnost pri maloj brzini', '<p>Šire gume često daju stabilan osećaj pri polasku i na manjim brzinama. To može prijati vozačima sa radnim teretom ili onima koji često staju.</p><p>Stabilan osećaj ne menja granice prianjanja. Mokra boja na kolovozu, lišće, ulje i led ostaju klizavi bez obzira na širinu.</p>'],
      ['Mana: veći otpor i masa', '<p>Šira i teža guma može povećati otpor kotrljanja i energiju potrebnu za ubrzanje. Motor deo toga prikriva, ali baterija i dalje isporučuje energiju. Na istoj ruti domet može zavisiti i od konstrukcije gume i pritiska.</p><p>Veća masa se oseća pri podizanju, transportu i vožnji bez asistencije. Ako bicikl unosite uz stepenice, ovo je važan kompromis.</p>'],
      ['Mana: dostupnost, cena i skladištenje', '<p>Široke gume i unutrašnje gume nisu uvek dostupne u svakoj prodavnici. Pre kupovine proverite dimenziju, preporučeni pritisak i dostupnost zamene. Blatobrani, nosači i brave takođe moraju odgovarati širini.</p><p>Bicikl zauzima više mesta u hodniku, nosaču ili prtljažniku. Standardni nosač za automobil možda neće prihvatiti vrlo širok profil bez adaptera.</p>'],
      ['Core i Cargo sa širokim gumama', '<p><a href="/elektricni-bicikli/core/">Pogon Core</a> kombinuje fat tyre gume sa sklopivim ramom i dve baterije. Namenjen je vozaču kome su važni stabilnost i odlaganje. <a href="/elektricni-bicikli/cargo/">Pogon Cargo</a> koristi široke gume u radnom modelu za dostavu i prevoz stvari.</p><p>Oba navode hidraulične kočnice, motor od 250 W i deklarisani domet do 140 km, ali njihova namena nije ista. Izbor treba da krene od tereta i potrebe za sklapanjem.</p>'],
      ['Kako izabrati pritisak i održavati gume', '<p>Počnite unutar raspona označenog na bočnoj strani gume ili u uputstvu. Prilagodite prema opterećenju i podlozi, ali ne izlazite iz propisanog raspona. Proveravajte pritisak hladne gume odgovarajućim meračem.</p><p>Pregledajte posekotine, strana tela, ispupčenja i istrošenost. Kod težeg e-bicikla stanje guma direktno utiče na kontrolu i zaustavljanje.</p>'],
    ],
    faq: [
      ['Da li fat tyre gume sprečavaju proklizavanje?', 'Ne. Mogu promeniti osećaj i kontakt sa podlogom, ali mokre i zaleđene površine i dalje zahtevaju oprez.'],
      ['Da li široke gume smanjuju domet?', 'Mogu povećati otpor i masu, ali stvarni uticaj zavisi od konstrukcije, pritiska, podloge i stila vožnje.'],
      ['Da li su dobre samo za teren?', 'Ne. Često se koriste i u gradu radi udobnosti na lošijem asfaltu, ali imaju kompromise u masi i efikasnosti.'],
    ],
    related: ['sklopivi-elektricni-bicikl', 'domet-elektricnog-bicikla', 'odrzavanje-elektricnog-bicikla'],
  },
  {
    slug: 'elektricni-bicikl-za-dostavu',
    title: 'Kako izabrati električni bicikl za dostavu?',
    description: 'Vodič za izbor električnog bicikla za kurire i dostavu: domet, baterije, kočnice, gume, teret, punjenje, servis i ukupni operativni trošak.',
    category: 'Posao i dostava',
    direct: 'Za dostavu su najvažniji pouzdan domet sa rezervom, kontrola pod teretom, vreme punjenja, dostupni delovi i servis. Maksimalni domet bez podataka o teretu i ruti nije dovoljan za odluku.',
    sections: [
      ['Mapirajte smenu, ne samo jednu vožnju', '<p>Zabeležite kilometražu tipične i duge smene, broj zaustavljanja, visinsku razliku i vreme provedeno u vožnji. Dostava ima mnogo ubrzanja iz mesta, što povećava potrošnju u odnosu na ravnomernu rekreativnu vožnju.</p><p>Dodajte rezervu za povratak, promenu zone i hladno vreme. Bicikl koji pokriva samo idealan prosek može postati operativni problem tokom zahtevnijeg dana.</p>'],
      ['Jedna ili dve baterije', '<p>Dve baterije mogu smanjiti vreme bez vožnje i dati veću rezervu. Važno je kako se koriste: da li se prebacivanje obavlja automatski, da li se baterije pune odvojeno i koliko punjača imate. Sve treba proveriti za konkretan model.</p><p>Ukupni Wh su korisniji od samog broja baterija. Dve male baterije nisu automatski bolje od jedne veće.</p>'],
      ['Teret i raspodela mase', '<p>Proverite deklarisanu nosivost bicikla i nosača, ne samo prostor koji torba zauzima. Težak teret postavljen visoko ili daleko iza zadnje osovine menja upravljanje i kočenje.</p><p>Teret pričvrstite tako da ne dodiruje točak, kočnicu ili svetla. Probajte polazak, sporu vožnju i zaustavljanje sa tipičnim opterećenjem pre ulaska u gust saobraćaj.</p>'],
      ['Kočnice i gume', '<p>Česta zaustavljanja i veća masa ubrzavaju habanje kočionih pločica. Važni su tip kočnica, dostupnost delova i jasna tačka hvatanja na ručici. Kontrola je važnija od marketinške etikete.</p><p>Šire gume mogu dati mirniji osećaj na lošem asfaltu, ali povećavaju masu i otpor. Redovno proveravajte pritisak jer teret dodatno opterećuje gumu.</p>'],
      ['Punjenje i vreme bez vožnje', '<p>Planirajte gde se baterija puni, koliko traje punjenje i da li prostor ima nadzor i odgovarajuće uslove. Nemojte improvizovati sa neodgovarajućim punjačem ili produžnim kablom koji se pregreva.</p><p>Ako se bicikl koristi u više smena, kapacitet nije jedino pitanje; važni su logistika punjenja i vreme hlađenja baterije posle intenzivne vožnje.</p>'],
      ['Servis i ukupni operativni trošak', '<p>Za posao je zastoj trošak. Proverite dostupnost guma, pločica, lanca, punjača i drugih delova. Vodite evidenciju kilometraže i kontrola kako biste reagovali pre otkaza.</p><p>U ukupni račun uključite energiju, potrošne delove, servis, opremu za zaključavanje i rezervni plan prevoza. <a href="/vodici/koliko-kosta-elektricni-bicikl-mesecno/">Vodič o mesečnom trošku</a> daje okvir bez izmišljenih cena.</p>'],
      ['Pogon Cargo za dostavu', '<p><a href="/elektricni-bicikli/cargo/">Pogon Cargo</a> je radni model sa dve baterije ukupnog kapaciteta 1512 Wh, deklarisanim dometom do 140 km, hidrauličnim kočnicama, širokim gumama i zadnjim motorom od 250 W.</p><p>Ti podaci ga čine prirodnim kandidatom za dostavu, ali stvarni domet treba proceniti sa teretom i rutom. Test vožnja treba da uključi polazak, okretanje, kočenje i parkiranje sa opremom koju zaista nosite.</p>'],
      ['Kontrolna lista pre smene', '<ul><li>pritisak i stanje obe gume;</li><li>rad prednjeg i zadnjeg svetla;</li><li>osećaj obe kočnice;</li><li>pričvršćenje baterije i tereta;</li><li>nivo energije i plan punjenja;</li><li>lanac i neuobičajeni zvuci;</li><li>brava, kaciga i oprema za vidljivost.</li></ul><p>Kratka svakodnevna kontrola je jeftinija od zastoja usred smene.</p>'],
    ],
    faq: [
      ['Koliki domet je dovoljan za dostavu?', 'Zavisi od dužine smene, terena, tereta i mogućnosti dopune. Planirajte rezervu iznad tipične kilometraže.'],
      ['Da li su dve baterije obavezne?', 'Ne, ali mogu biti korisne za duge smene. Važniji je ukupni kapacitet u Wh i logistika punjenja.'],
      ['Koliko često treba servisirati dostavni e-bicikl?', 'Interval zavisi od kilometraže i uslova. Svakodnevne osnovne kontrole i servis prema uputstvu i habanju su važniji od jednog univerzalnog roka.'],
    ],
    related: ['domet-elektricnog-bicikla', 'fat-tyre-elektricni-bicikl', 'odrzavanje-elektricnog-bicikla'],
  },
  {
    slug: 'elektricni-bicikl-za-grad',
    title: 'Kako izabrati električni bicikl za gradsku vožnju?',
    description: 'Kako birati gradski električni bicikl prema ruti, položaju sedenja, bateriji, odlaganju, gumama, kočnicama, sigurnosti i test vožnji.',
    category: 'Gradska vožnja',
    direct: 'Za grad birajte e-bicikl prema svakodnevnoj ruti, udobnosti, načinu odlaganja i sigurnosti. Domet treba da pokrije odlazak, povratak i rezervu; položaj sedenja i osećaj kočnica proverite na test vožnji.',
    sections: [
      ['Definišite tipičan gradski dan', '<p>Napišite koliko kilometara prelazite, gde parkirate, da li nosite laptop ili kupovinu i koliko često nailazite na uspon. Uključite put do posla i povratak, a ne samo jednu deonicu.</p><p>Razmislite gde će bicikl biti tokom noći. Ulična brava, zajednička garaža i stan imaju različite zahteve za masu, sklapanje i sigurnosnu opremu.</p>'],
      ['Udobnost i položaj sedenja', '<p>Gradska vožnja uključuje mnogo gledanja oko sebe, polazaka i zaustavljanja. Upravljač i sedište treba podesiti tako da možete kontrolisano stati i pogledati preko ramena bez gubitka ravnoteže.</p><p>Na test vožnji provedite dovoljno vremena da osetite pritisak na šakama i sedištu. Krug od jednog minuta ne otkriva sve.</p>'],
      ['Domet sa gradskom rezervom', '<p>Za ravne kratke rute velika baterija možda nije neophodna. Za duže relacije, hladno vreme ili više obaveza rezervni kapacitet smanjuje brigu. Deklarisani maksimum tretirajte kao gornju vrednost, ne kao plan.</p><p>Pročitajte <a href="/vodici/domet-elektricnog-bicikla/">šta utiče na stvarni domet</a> i izmerite svoju rutu pre poređenja modela.</p>'],
      ['Ram, sklapanje i stepenice', '<p>Aluminijumski ram se često bira radi odnosa mase i čvrstoće, dok čelični ram može nuditi drugačiji osećaj i konstrukciju. Materijal sam ne određuje udobnost; geometrija i ukupna masa su jednako važni.</p><p>Ako nemate lift, probajte da podignete bicikl. Ako je prostor ograničen, <a href="/vodici/sklopivi-elektricni-bicikl/">sklopivi model</a> može pomoći, ali i dalje proverite težinu.</p>'],
      ['Gume i gradska podloga', '<p>Klasične gradske gume obično su efikasnije na dobrom asfaltu. Šire gume mogu doneti mirniji osećaj preko šahtova i neravnina, uz veći otpor i masu.</p><p>Izbor zavisi od ulica kojima stvarno vozite. Ne birajte terenski izgled ako većinu vremena provodite na glatkoj biciklističkoj stazi i morate bicikl nositi.</p>'],
      ['Kočnice, svetla i sigurnost', '<p>Proverite da obe kočnice hvataju predvidljivo i da ručice odgovaraju šaci. Svetla treba da budu vidljiva, a reflektujući elementi čisti. Retrovizor može pomoći u praćenju saobraćaja, ali ne zamenjuje pogled preko ramena.</p><p>Kvalitetna brava i način vezivanja za čvrst predmet važni su za svako duže parkiranje. GPS i NFC funkcije mogu biti dodatni slojevi, ali fizičko zaključavanje ostaje važno.</p>'],
      ['Glide ili Core?', '<p><a href="/elektricni-bicikli/glide/">Pogon Glide</a> je usmeren na klasičnu gradsku vožnju, ima aluminijumski ram, bateriju 1200 Wh, deklarisani domet do 90 km i NFC kartice. <a href="/elektricni-bicikli/core/">Pogon Core</a> dodaje sklopivi čelični ram, široke gume i dve baterije ukupno 1512 Wh, uz deklarisani domet do 140 km.</p><p>Glide birajte kada želite jednostavan gradski format; Core kada su sklapanje, široke gume i veća energetska rezerva važniji od manje mase i klasične geometrije.</p>'],
      ['Šta probati na test vožnji', '<ul><li>polazak u najnižem nivou asistencije;</li><li>sporo okretanje u uskom prostoru;</li><li>zaustavljanje i ponovno kretanje;</li><li>kratak uspon ako je deo vaše rute;</li><li>kočenje progresivnim pritiskom;</li><li>skidanje baterije ili sklapanje, ako ćete to redovno raditi.</li></ul><p>Ponesite ranac ili torbu koju obično koristite da biste proverili realan položaj i ravnotežu.</p>'],
    ],
    faq: [
      ['Koliki domet je potreban za grad?', 'Izračunajte dnevni odlazak i povratak, dodajte neplanirane obaveze i ostavite rezervu za hladnoću, vetar i starenje baterije.'],
      ['Da li su široke gume potrebne u gradu?', 'Nisu obavezne. Mogu pomoći na lošem asfaltu, ali povećavaju masu i otpor.'],
      ['Da li je sklopivi model bolji za stan?', 'Može zauzimati manje prostora, ali proverite masu, dimenzije i koliko ga je lako nositi.'],
    ],
    related: ['kako-izabrati-elektricni-bicikl', 'sklopivi-elektricni-bicikl', 'domet-elektricnog-bicikla'],
  },
  {
    slug: 'odrzavanje-elektricnog-bicikla',
    title: 'Održavanje električnog bicikla: šta treba redovno proveravati',
    description: 'Praktična kontrolna lista za održavanje električnog bicikla: gume, kočnice, lanac, ram, baterija, kablovi, čišćenje i servis.',
    category: 'Održavanje',
    direct: 'Pre vožnje proverite gume, kočnice, svetla i pričvršćenje baterije. Redovno čistite pogon, pratite habanje kočnica i čuvajte bateriju od vode, udara i ekstremnih temperatura.',
    sections: [
      ['Kratka kontrola pre svake vožnje', '<p>Stisnite kočnice, pogledajte da li su gume vidljivo oštećene i proverite svetla. Baterija treba da bude pravilno zaključana, a sklopivi mehanizam potpuno zatvoren ako ga model ima.</p><p>Obratite pažnju na nov zvuk, vibraciju ili promenu u upravljanju. Rano primećena promena često je jednostavnija za rešavanje od otkaza na putu.</p>'],
      ['Pritisak i stanje guma', '<p>Pritisak proveravajte meračem dok su gume hladne, u okviru oznake na gumi ili uputstva proizvođača. Prenizak pritisak povećava otpor, zagrevanje i rizik oštećenja; previsok može smanjiti udobnost i kontakt na neravninama.</p><p>Pregledajte gazni sloj, bočne zidove, posekotine i strana tela. Kod teškog e-bicikla ili tereta stanje guma posebno utiče na kočenje.</p>'],
      ['Kočnice', '<p>Ručica ne treba da propada do upravljača niti da menja tačku hvatanja bez razloga. Slušajte struganje i proverite debljinu pločica prema uputstvu. Mokri uslovi i dostava mogu ubrzati habanje.</p><p>Kočione površine ne mažite i ne dodirujte masnim rukama. Ako niste sigurni kako se podešavaju ili odzračuju hidraulične kočnice, prepustite posao kvalifikovanom servisu.</p>'],
      ['Lanac i prenos', '<p>Prljav lanac povećava habanje i buku. Očistite ga odgovarajućim sredstvom, osušite i nanesite mazivo namenjeno uslovima vožnje. Višak obrišite da ne privlači prljavštinu.</p><p>Menjajte brzine bez grubog opterećenja kada je moguće. Preskakanje, krckanje ili vidljivo istezanje zahtevaju proveru lanca i zupčanika.</p>'],
      ['Baterija, kontakti i punjač', '<p>Kućište baterije treba da bude bez pukotina i deformacija. Kontakte držite čistim i suvim bez metalnih predmeta koji mogu izazvati kratki spoj. Koristite odgovarajući punjač i proverite kabl pre priključivanja.</p><p>Ne perite bateriju mlazom pod pritiskom. Za punjenje i skladištenje pratite uputstvo konkretnog modela. Više detalja je u <a href="/vodici/baterija-elektricnog-bicikla/">vodiču o bateriji e-bicikla</a>.</p>'],
      ['Ram, točkovi i pričvršćenja', '<p>Pregledajte ram oko spojeva, nosača i mesta na kojima se montira teret. Proverite da točkovi nemaju neuobičajen bočni hod i da nema labavih delova. Vijke zatežite samo odgovarajućim momentom iz uputstva.</p><p>Kod sklopivog modela proverite sigurnosni zatvarač posle svakog sklapanja. Kod cargo upotrebe proverite nosač i vezivanje tereta pre svake smene.</p>'],
      ['Čišćenje bez štete elektronici', '<p>Koristite vlažnu krpu, meku četku i blago sredstvo. Izbegavajte usmeren visok pritisak prema ležajevima, motoru, displeju, bateriji i konektorima. Posle mokre vožnje obrišite bicikl i ostavite ga da se osuši na provetrenom mestu.</p><p>Prljavština oko kočnica i pogona nije samo estetski problem; otežava pregled i može ubrzati habanje.</p>'],
      ['Kada je potreban servis', '<p>Servis zatražite kod promene u kočenju, lufta u upravljaču ili točku, oštećenja kabla, greške sistema, neobičnog zagrevanja baterije ili naglog pada dometa. Ne otvarajte motor, bateriju ili kontroler bez stručnog znanja.</p><p>Pogon navodi servisnu podršku u više gradova. Najbližu lokaciju, dostupne usluge i radno vreme treba potvrditi porukom ili pozivom; ovaj vodič ne pretpostavlja uslugu koja nije unapred dogovorena.</p>'],
      ['Jednostavan raspored', '<table class="data-table"><thead><tr><th>Učestalost</th><th>Provera</th></tr></thead><tbody><tr><td>Pre vožnje</td><td>Gume, kočnice, svetla, baterija, labavi delovi</td></tr><tr><td>Redovno</td><td>Pritisak, lanac, pločice, čišćenje i kontakti</td></tr><tr><td>Posle kiše ili tereta</td><td>Sušenje, kočnice, pogon i nosači</td></tr><tr><td>Po uputstvu / simptomu</td><td>Stručni servis i elektronska dijagnostika</td></tr></tbody></table><p>Tačan interval zavisi od modela, kilometraže i uslova. Uputstvo proizvođača ima prednost nad opštom tabelom.</p>'],
    ],
    faq: [
      ['Da li e-bicikl sme da se pere mlazom pod pritiskom?', 'Visok pritisak može potisnuti vodu u ležajeve i elektroniku. Bezbedniji su vlažna krpa, meka četka i pažljivo sušenje.'],
      ['Koliko često proveravati pritisak?', 'Redovno i pre dužih vožnji, naročito sa teretom. Guma može izgubiti pritisak pre nego što izgleda prazno.'],
      ['Da li električni deo traži poseban servis?', 'Da. Bateriju, motor i kontroler ne treba otvarati bez stručnog znanja i odgovarajuće opreme.'],
      ['Šta uraditi posle vožnje po kiši?', 'Obrišite bicikl, osušite ga na provetrenom mestu i proverite kočnice, pogon i konektore bez otvaranja elektronike.'],
    ],
    related: ['baterija-elektricnog-bicikla', 'domet-elektricnog-bicikla', 'koliko-kosta-elektricni-bicikl-mesecno'],
  },
];

export const cities = [
  {
    slug: 'beograd',
    name: 'Beograd',
    locative: 'Beogradu',
    title: 'Električni bicikli Beograd | Pogon test vožnja',
    description: 'Zakažite Pogon test vožnju električnog bicikla u Beogradu. Uporedite Core, Cargo i Glide uz unapred potvrđen termin i lokaciju.',
    localNote: 'Beogradske rute često kombinuju gust saobraćaj, zaustavljanja i uspone. Na probi izaberite deonicu koja liči na vaš put do posla i obratite pažnju na polazak, kočenje i potrošnju na usponu.',
    planning: 'Pre termina opišite da li je vaša svakodnevna ruta pretežno ravna ili uključuje duže uspone i mnogo semafora. Ako bicikl treba da zamenjuje automobil na putu do posla, proverite sporu kontrolu u gustim raskrsnicama, lakoću silaska sa bicikla i koliko stabilno možete da krenete posle zaustavljanja. Za duže relacije zabeležite potrošnju na delu rute koji najviše liči na vaš uobičajeni pravac.',
  },
  {
    slug: 'novi-sad',
    name: 'Novi Sad',
    locative: 'Novom Sadu',
    title: 'Električni bicikli Novi Sad | Pogon test vožnja',
    description: 'Zakažite Pogon test vožnju električnog bicikla u Novom Sadu. Probajte Core, Cargo ili Glide uz unapred potvrđen termin i lokaciju.',
    localNote: 'Na ravnijim gradskim rutama važno je proceniti položaj sedenja, ponašanje pri čestim raskrsnicama i uticaj vetra na potrošnju. Ponesite opremu koju obično nosite.',
    planning: 'Na ravnijoj probi lako se poredi koliko prirodno rade različiti nivoi asistencije, ali uključite i deonicu izloženu vetru ako je to deo vaše rutine. Proverite preglednost, okretanje pri maloj brzini i udobnost preko spojeva i neravnina. Ako bicikl kombinujete sa zgradom bez velike ostave, kod modela Core obavezno probajte sklapanje i procenite masu pri podizanju.',
  },
  {
    slug: 'nis',
    name: 'Niš',
    locative: 'Nišu',
    title: 'Električni bicikli Niš | Pogon test vožnja',
    description: 'Zakažite Pogon test vožnju električnog bicikla u Nišu. Uporedite namenu i domet modela Core, Cargo i Glide.',
    localNote: 'Za rute koje uključuju uspon izaberite probu sa promenom nagiba i proverite kako vam odgovaraju nivoi asistencije. Toplota, teret i pritisak u gumama takođe menjaju domet.',
    planning: 'Ako vaša ruta prelazi iz ravnog dela u uspon, probajte pravovremenu promenu prenosa i nekoliko nivoa asistencije umesto samo najjačeg. U toplijem periodu planirajte punjenje i čuvanje baterije van direktnog sunca. Za svakodnevne obaveze proverite da li vam položaj sedenja ostavlja dobru preglednost i sigurnu kontrolu pri čestim polascima.',
  },
  {
    slug: 'kragujevac',
    name: 'Kragujevac',
    locative: 'Kragujevcu',
    title: 'Električni bicikli Kragujevac | Pogon test vožnja',
    description: 'Zakažite Pogon test vožnju električnog bicikla u Kragujevcu. Probajte gradski, sklopivi ili cargo model uz potvrđen termin.',
    localNote: 'Promena nagiba i mešovite gradske površine čine probu korisnom za izbor baterije, guma i položaja sedenja. Testirajte kontrolisan polazak i zaustavljanje na ruti sličnoj vašoj.',
    planning: 'Za rutu sa promenljivim nagibom proverite kako bicikl prelazi iz nižeg u viši nivo asistencije i kako se ponaša pri kontrolisanom kočenju niz blag pad. Ako vozite do posla, ponesite tipičan ranac. Ako prevozite robu ili alat, opišite približnu masu kako biste sa timom procenili da li je Cargo prikladniji od gradskog modela.',
  },
];
